# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic
import sys
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
from PyQt5.QtWidgets import QAction
import numpy as np
import matplotlib.pyplot as plt

class CustomNavigationToolbar(NavigationToolbar):
    def __init__(self, canvas, parent, coordinates=True):
        NavigationToolbar.__init__(self, canvas, parent, coordinates)
        self.save_text_action = QAction('Save as Text', self)
        self.save_text_action.triggered.connect(self.save_plot_as_text)
        self.addAction(self.save_text_action)

    def save_plot_as_text(self):
        fig = self.canvas.figure
        for ax in fig.axes:
            for line in ax.lines:
                x_data = line.get_xdata()
                y_data = line.get_ydata()
                np.savetxt(f'{line.get_label()}.txt', np.column_stack((x_data, y_data)), delimiter=',', header='X,Y', comments='')
        print("Plot data saved as text files.")


class Ui_MainWindow(QtWidgets.QMainWindow):
    
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        uic.loadUi('interface.ui', self)
        self.setupMatplotlib()
    
    def setupMatplotlib(self):
        self.figure = plt.figure()
        self.canvas = FigureCanvas(self.figure)
        #self.toolbar = NavigationToolbar(self.canvas, self)
        self.toolbar = CustomNavigationToolbar(self.canvas, self)

        layout = QtWidgets.QVBoxLayout(self.matplotlibWidget)
        layout.addWidget(self.toolbar)
        layout.addWidget(self.canvas)

        self.plot()

    def plot(self):
        data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        ax = self.figure.add_subplot(111)
        ax.plot(data, '*-')
        self.canvas.draw()
    
    def setupUi(self, MainWindow): 

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(466, 402)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(300, 170))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(212, 228, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setText("Slider 1:")
        self.horizontalLayout.addWidget(self.label1)

        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)

        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setText("Slider 2:")
        self.horizontalLayout.addWidget(self.label2)


        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout.addWidget(self.horizontalSlider_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("Group Box")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.addWidget(self.groupBox)

        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 466, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = Ui_MainWindow()
    window.show()
    sys.exit(app.exec_())
